version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER= owolarafe
      - POSTGRES_PASSWORD= owolarafe
  
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"