version: '3'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - pgdb
      - redis
  celery:
    build: .
    command: celery -A aBlog worker -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
  pgdb:
    image: postgres
    container_name: pgdb
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER= owolarafe
      - POSTGRES_PASSWORD= owolarafe
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
      image: "redis:alpine"
  # web:
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "8000:8000"
volumes:
  pgdata: