# Generated by Django 4.0.4 on 2022-05-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default="What's happening? "),
        ),
    ]
