# Generated by Django 4.0.4 on 2022-05-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0005_post_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorised', max_length=225),
        ),
    ]
