# Generated by Django 4.0.4 on 2022-05-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0016_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='User',
            new_name='user',
        ),
    ]
