name: Testing
on: push

jobs:
  test_project:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up python
    - uses: actions/setup-python@v2
      with: 
        python-version: ["3.8", "3.9", "3.10", "3.11.0-beta.3"]
    - name: Run Django unit tests
      run:
        pip install --user django
        python manage.py test