name: Testing
on: push

jobs:
  test_project:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout VM
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
    - name: Run Django unit tests
      run:
        pip install -r requirements.txt && python manage.py test